---
title: "Prueba de creacion de modelo de efectos mixtos"
author: "Joaquin Cerviño, Dario Ruiz y Esteban Lombera"
date: "09/23/2021"
output:
  html_document:
    code_folding: show
    df_print: paged
    theme: united
    highlight: pygments
    toc: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
library(purrr)
library(dplyr)
library(ggpubr)
library(nlme)
library(car)
```

## Prueba de modelo de efectos mixtos
<style>
body {
text-align: justify}
</style>
Esta es una prueba de creación de un modelo de efectos mixtos
Voy a considerar fecha condicion y tiempo como efectos fijos y punto como 
efecto aleatorio.
<style>
.html-widget {
    margin: auto;
}
</style>
```{r fig-margin1, fig.margin=TRUE, fig.dim = c(9, 4)}
tabla.datos = read.csv("./data/datosR.csv", header = TRUE, sep = ';', stringsAsFactors = TRUE)

# tengo un problema de encoding con la ñ de columna Año Nuevo
tabla.datos %<>% mutate(fecha = case_when(
  fecha != 'Navidad' ~ 'Anio_nuevo',
  fecha == 'Navidad' ~ 'Navidad',
))

tabla.datos %<>%
  mutate(condicion = case_when(
    tiempo <= 3600 ~ 'sin_pirotecnia',
    tiempo > 3600 ~ 'con_pirotecnia',
  ))

pirotecnia.lme <- lme(nivel_sonoro ~ fecha*condicion*tiempo, data = tabla.datos, random = ~ 1|punto)

summary(pirotecnia.lme)

```
<br />
<style>
body {
text-align: justify}
</style>
El anova
<br />
```{r echo=TRUE,fig-margin2}
Anova(pirotecnia.lme)

```
<br />
<style>
body {
text-align: justify}
</style>
Y los residuos
<br />
```{r fig-margin3, fig.margin=TRUE, fig.dim = c(9, 4)}
residuo_datos2 <- tabla.datos %>% mutate(res = resid(pirotecnia.lme )) %>% tibble()
p3 = ggplot(residuo_datos2, aes(x = res, y = tabla.datos$punto)) + geom_boxplot()
p3

```

<br />
<style>
body {
text-align: justify}
</style>
El modelo junto con los datos
<br />
```{r fig-margin4, fig.margin=TRUE, fig.dim = c(9, 4)}

data_m1.lm <- tabla.datos %>% mutate(pred = predict(pirotecnia.lme), res = resid(pirotecnia.lme))

figura2 = ggplot(tabla.datos, aes(x=tiempo, y=nivel_sonoro))+
  geom_point(alpha = 0.3)+
  facet_grid(fecha~punto)+
  theme_pubr(base_size = 12, margin = TRUE)+
  scale_x_continuous(name= "Tiempo [seg]", breaks=c(0,3500,7000), labels=c("0","3k5","7k")) +
  labs(y = "Nivel de presión [dBA]") +
  theme(legend.position = "top",
        legend.title = element_blank())+
  geom_line(data=data_m1.lm, aes(x=tiempo, y=pred, group=punto), color='white')

figura2
```